FROM ruby:2.7.0-slim-buster

RUN apt-get update &&\
    apt-get install -y git vim build-essential patch ruby-dev zlib1g-dev liblzma-dev libpq-dev libsqlite3-dev &&\
    rm -rf /var/lib/apt/lists/*

RUN gem update --system 3.1.2 &&\
    gem install bundler -v '2.1.2'


WORKDIR /usr/src/app/alpha-blog

COPY . .

ENV BUNDLER_VERSION 2.1.2

RUN bundle update &&\
    bundle install &&\
    rails db:setup &&\
    rails db:migrate

EXPOSE 3000

CMD ["rails", "server", "-b", "0.0.0.0"]   
